language: swift
osx_image: xcode11.3
os: osx
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="SCrypto.xcworkspace"
  - IOS_FRAMEWORK_SCHEME="SCrypto iOS"
  - OSX_FRAMEWORK_SCHEME="SCrypto OSX"
  - IOS_SDK=iphonesimulator13.2
  - OSX_SDK=macosx10.15
  matrix:
    - DESTINATION="arch=x86_64"                     SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     BUILD="YES" POD_LINT="NO"
    - DESTINATION="OS=12.4,name=iPhone 8"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     BUILD="YES" POD_LINT="YES"
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - gem install slather --no-document --quiet
  - cd $TRAVIS_BUILD_DIR
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $BUILD == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c;
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES clean build test | xcpretty -c;
    fi

  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f slather/cobertura.xml -X coveragepy -X gcov -X xcode
notifications:
  email: false